[project]
name = "streamlit-agent-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.93.0",
    "openai-agents>=0.1.0",
]
